name: Install GROMACS

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7",]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Bash Requirements
        run: |
        
          sudo apt update
          sudo apt upgrade
          sudo apt install gcc
          sudo apt install cmake
          sudo apt install build-essential
          sudo apt-get install -y libfftw3-dev
          
      - name: Install GROMACS Requirements
        run: |
          wget https://ftp.gromacs.org/gromacs/gromacs-2023.3.tar.gz
          tar -xfz gromacs-2023.3.tar.gz
          cd gromacs-2023.3
          mkdir build
          cd build
          cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON
          make
          make check
          sudo make install
          source /usr/local/gromacs/bin/GMXRC
